<template>
  <UCard>
    <template #header>
      <div class="flex justify-between items-center">
        <span class="font-medium"
          >{{ useGroups().getGroupByID(groupID).name }} - Settings</span
        >
        <UButton
          @click="$emit('close')"
          variant="ghost"
          color="gray"
          icon="i-heroicons-x-mark"
        />
      </div>
    </template>
    <div class="space-y-4">
      <UTabs color="primary" :items="tabs">
        <template #item="{ item }">
          <div v-if="item.label === 'General'" class="space-y-2">
            <UFormGroup label="Group Name">
              <UInput
                @blur="updateName"
                placeholder="New Group"
                v-model="name"
              />
            </UFormGroup>
            <UFormGroup label="Currency Symbol">
              <UInput
                @blur="updateCurrency"
                placeholder="ex: $ or ₹"
                v-model="currency"
              />
            </UFormGroup>
            <SplitwiseImport />
            <SupabaseImport />
            <CsvExport />
            <UDivider />
            <UFormGroup label="Share Group Summary">
              <p class="text-xs text-gray-400 dark:text-gray-500 mb-2">
                Copy a text summary of all expenses and balances in this group to your clipboard.
              </p>
              <UButton
                @click="copySummary"
                color="primary"
                variant="soft"
                block
                icon="i-heroicons-document-text"
              >
                {{ copiedSummary ? 'Copied!' : 'Copy Summary' }}
              </UButton>
            </UFormGroup>
          </div>
          <GroupSettingsMembers v-if="item.label === 'Members'" />
          <GroupSettingsBalances v-if="item.label === 'Balances'" />
        </template>
      </UTabs>
    </div>
  </UCard>
</template>

<script setup>
const groupID = useGroupID();
const copiedSummary = ref(false);
const tabs = [
  { label: "General", icon: "i-heroicons-user-circle" },
  { label: "Members", icon: "i-heroicons-user-group" },
  { label: "Balances", icon: "i-heroicons-document-currency-dollar" },
];
const name = ref(useGroups().getGroupByID(groupID)?.name),
  currency = ref(useGroups().getGroupByID(groupID)?.currency);
function updateName() {
  useGroups().setGroupName(groupID, name.value);
}
function updateCurrency() {
  useGroups().setGroupCurrency(groupID, currency.value);
}
function copySummary() {
  const group = useGroups().getGroupByID(groupID);
  const currency = group?.currency || "₹";
  const members = Object.values(group?.members || {});
  const transactions = Object.values(group?.transactions || {});
  const balances = groupGetBalances(group);
  const payments = groupGetPayments(group);

  let text = `📊 ${group?.name || "Group"} - Expense Summary\n`;
  text += `━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

  // Members
  text += `👥 Members (${members.length}):\n`;
  for (const m of members) {
    const tag = m.id === group?.myID ? " (You)" : "";
    const bal = balances[m.id];
    const balStr = bal !== undefined
      ? bal > 0 ? ` +${currency}${bal}` : bal < 0 ? ` ${currency}${Math.abs(bal)}` : " settled"
      : "";
    text += `  • ${m.name}${tag} — ${balStr}\n`;
  }
  text += `\n`;

  // Expenses count
  const expenseCount = transactions.filter(t => t.type === "expense").length;
  const paymentCount = transactions.filter(t => t.type === "payment").length;
  text += `💳 ${expenseCount} expense${expenseCount !== 1 ? "s" : ""}`;
  if (paymentCount > 0) text += `, ${paymentCount} payment${paymentCount !== 1 ? "s" : ""}`;
  text += `\n`;

  // Total spent
  let totalSpent = 0;
  for (const tx of transactions) {
    const computed = computeTransaction(tx);
    totalSpent += computed.totalCost;
  }
  text += `💰 Total spent: ${currency}${round(totalSpent)}\n\n`;

  // Outstanding debts
  if (payments.length > 0) {
    text += `📋 Outstanding Debts:\n`;
    for (const p of payments) {
      const fromName = useGroups().getMemberName(group.id, p.from);
      const toName = useGroups().getMemberName(group.id, p.to);
      text += `  • ${fromName} → ${toName}: ${currency}${p.value}\n`;
    }
  } else {
    text += `✅ All settled up!\n`;
  }

  text += `\n━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  text += `Generated by PeerSplit`;

  navigator.clipboard.writeText(text);
  copiedSummary.value = true;
  setTimeout(() => { copiedSummary.value = false; }, 2000);
}
</script>
